declare -A cases

cases[1]="Settle or fight?  Far Eastern Economic Review  and Singapore"
cases[2]="Frontline's 'The Last Abortion Clinic': What's Fair in a Video World?"
cases[9]="New England Cable News and the Terry Glenn Story (Video)"
cases[12]="Chemical Fallout: The Milwaukee Journal Sentinel and the BPA Story"
cases[14]="Reporting an Explosive Truth: The Boston Globe and Sexual Abuse in the Catholic Church "
cases[15]="Charting a Course for Change: Transforming the Albany Times Union in a Wired World"
cases[16]="From Concept to Story: Time Magazine and 'America at 300 Million'"
cases[17]="The Bakersfield Californian and Blogging the Courtroom"
cases[18]="New England Cable News and the Terry Glenn Story"
cases[19]="Crowdsourcing: Promise or Hazard? Part A: Debate at the Fort Myers, FL, News-Press"
cases[20]="Crowdsourcing at the Fort Myers, FL, News-Press Part B: 'Help Us Investigate'"
cases[21]="Integrity on Deadline: ABC News and the Duke Lacrosse Photographs"
cases[22]="Reputations to Lose: BBC versus the Blair Government"
cases[23]="After the Storms: The South Florida Sun-Sentinel Investigates FEMA"
cases[24]="A Life on the Line: The Christian Science Monitor and Jill Carroll"
cases[25]="Public Death, Private Life: Army Major Alan Rogers and the  Washington Post"
cases[27]="Privacy and the Public Interest: Frederick, MD, News-Post and the Bruce Ivins Story"
cases[28]="News or Rumor? Politico and the Edwards Affair"
cases[29]="Digital Deadline: The St. Louis Post-Dispatch and the Kirkwood Shooting"
cases[30]="God and Darwin: The York Daily Record and the Intelligent Design Trial"
cases[31]="Elusive Story (dead)"
cases[33]="Terror or Accident? Newsday and the Crash of American Airlines Flight 587"
cases[34]="Terror or Accident? Newsday and the Crash of American Airlines Flight 587 (Video)"
cases[35]="Privacy and the Public Interest. Part B: The Case Against Ivins (DEAD)"
cases[36]="But is it News? The New York Times and the International Freedom Center"
cases[37]="A Matter of Opinion: The Oregonian Editorial Board and Sam Adams "
cases[38]="Risky Business: John Harris, Jim VandeHei, and Politico Part A"
cases[39]="Risky Business: John Harris, Jim VandeHei, and Politico Part B: A Winning Model?"
cases[40]="Elusive Story: The Chicago Tribune Examines 'No Child Left Behind'"
cases[43]="When the story is us: Miami Herald, Nuevo Herald and Radio Martí"
cases[49]="Reporters or cops? CONTACTO and the search for Paul Schaefer"
cases[50]="¿Periodistas o policías? CONTACTO y la búsqueda de Paul Schaefer"
cases[51]="Not for Profit? The Voice of San Diego Experiment"
cases[53]="The Facebook Conundrum: The New Haven Independent and the Annie Le Murder"
cases[54]="Voices Behind Bars: National Public Radio and Angola State Prison"
cases[55]="Into the Breach: Should Student Journalists Save Local Political Reporting?"
cases[56]="Legal Jeopardy: Clarín Group and the Kirchners"
cases[57]="Conflicted: The New York Times and the Bias Question"
cases[59]="Worth a Thousand Words: The Associated Press and Lance Corporal Joshua Bernard"
cases[60]="Privacidad y el Interés Público: Frederick, MD, News-Post y la Historia de Bruce Ivins. Primera Parte."
cases[61]="Privacidad e Interés Público: La Evidencia Contra Ivins. Segunda Parte."
cases[62]="Una Historia Esquiva: El Chicago Tribune y la ley 'Que Ningún Niño Quede Atrás'"
cases[66]="Caricatured: Le Monde and the Mohammed Cartoons"
cases[67]="Buy It or Make It? The Charlotte Observer and the Associated Press"
cases[68]="The Jury is Out: The Long Beach Post and Online Local News"
cases[69]="Dissonance: The Cleveland Plain Dealer and its Classical Music Critic"
cases[70]="Friend or foe? WikiLeaks and the Guardian"
cases[83]="Rating Teachers: a Job for Journalists? The Los Angeles Times and "Value-Added" Analysis"
cases[84]="Grow Your Own? Rice Self-sufficiency in Timor-Leste"
cases[85]="A Woman's Place? Photojournalist Lynsey Addario in Libya"
cases[86]="Personal Foul? Deadspin and an Iconic Athlete"
cases[87]="When BEST Intentions Go Awry: Arsenic Mitigation in Bangladesh"
cases[90]="Community Savings, or Community Threat? California Policy for Ill and Elderly Inmates"
cases[91]="Voluntary or Regulated? The Trans Fat Campaign in New York City"
cases[92]="Mission vs Safety: OCHA Somalia and the Baidoa Raid"
cases[106]="Words of the Dying: CHCH TV and Constable Garrett Styles"
cases[108]="Truthiness: This American Life and the Monologist"
cases[109]="¿Amigo o enemigo? Wikileaks y the Guardian "
cases[110]="Higher Truth or Just the Facts? Hell and Back Again"
cases[111]="Can Investigative Journalism Pay?: InvestigateWest and the Nonprofit Model"
cases[112]="Credible Voice: WHO-Beijing and the SARS Crisis"
cases[113]="Evacuate or Stay? Northshore LIJ and Hurricane Sandy"
cases[114]="The Elusive Tuberculosis Case: The CDC and Andrew Speaker"
cases[115]="Reportear una Verdad Explosiva: Boston Globe y los Abusos Sexuales  en la Iglesia Católica"
cases[116]="Cumulative or Discrete Numbers: How Should Bloomberg Measure the Bailout?"
cases[117]="Land Grab or Responsible Development? Oil Palm Concessions in Liberia"
cases[118]="AllNovaScotia.com: Success or Anomaly?"
cases[119]="A Newsroom Divided: Kenya, the Election Crisis, and the Nation Media Group"
cases[120]="Radio Buddu and the Uganda Anti-Homosexuality Bill"
cases[121]="Public Service or Illegal Act? The Weekly Mail and Bugging Staal Burger"
cases[122]="Spike or Suffer? Jamhuri and the Bribe Offer"
cases[123]="Seeking Partners for Press Freedom Media Council of Tanzania and DEFIR"
cases[124]="Côte Sud Initiative: Integrated Development in Haiti"
cases[125]="Scientific Method in the Real World: Experience Corps and the Johns Hopkins Study"
cases[126]="Fighting Blackmail: Khadija Ismayilova and Azerbaijan’s First Family"
cases[127]="From Compstat to Gov 2.0 Big Data in New York City Management"
cases[128]="Public-Private Partnerships for Green Space in NYC"
cases[129]="Salvation or Mirage? The New York Times Paywall"
cases[130]="Fighting for Equality in Education: Student Activism in Post-apartheid South Africa"
cases[131]="Tortoise or Hare? Fundación Carvajal and Buenaventura"
cases[132]="Chasing the Community Newspaper Rainbow: The Whiteville News Reporter and the Digital Age"
cases[133]="The Islanders and the Scientists: Post-tsunami Aid in the Nicobars"
cases[134]="Merging Two Worlds?: Reston Dental Arts and American Dental Partners"
cases[135]="Publishing Pollution Data in China: Ma Jun and the Institute of Public and Environmental Affairs"
cases[136]="Process and Politics: Chinalco and the Resettlement of Morococha"
cases[142]="Catalyze Without Offense: Daily Nation Living Magazine and the 'Laura' Story"
cases[146]="Swaziland, HIV and Option B+: What Can We Afford?"
cases[147]="Covert Activity: the Washington Post, Edward Snowden and the National Security Agency"
cases[148]="Just Enough Alarm: GlobalPost and the Syrian Chemical Attack S"


for i in "${!cases[@]}"
do
  touch case_$i.md
  echo --- >> case_$i.md
  echo author: >> case_$i.md
  echo date: >> case_$i.md
  echo id: "\"$i"\" >> case_$i.md
  echo title: "\"${cases[$i]}"\" >> case_$i.md
  echo --- >> case_$i.md
done
